title: Notes by Paul Gauthier
description: Personal blog and imported writing
permalink: /:year/:month/:day/:title/
markdown: kramdown
url: "https://paulg.info"
baseurl: ""

plugins:
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib

exclude:
  - vendor
  - tmp
  - tmp*

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "_posts/aider"
      type: "posts"
    values:
      layout: post
      imported_from: aider
      original_site: https://aider.chat
      original_blog_home: https://aider.chat/blog/
